// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ZZZ_TextMap.Defs
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TextMap : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static TextMap GetRootAsTextMap(ByteBuffer _bb) { return GetRootAsTextMap(_bb, new TextMap()); }
  public static TextMap GetRootAsTextMap(ByteBuffer _bb, TextMap obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TextMap __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Key { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetKeyBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetKeyArray() { return __p.__vector_as_array<byte>(4); }
  public string Text { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTextBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTextBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTextArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<ZZZ_TextMap.Defs.TextMap> CreateTextMap(FlatBufferBuilder builder,
      StringOffset keyOffset = default(StringOffset),
      StringOffset textOffset = default(StringOffset)) {
    builder.StartTable(2);
    TextMap.AddText(builder, textOffset);
    TextMap.AddKey(builder, keyOffset);
    return TextMap.EndTextMap(builder);
  }

  public static void StartTextMap(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddKey(FlatBufferBuilder builder, StringOffset keyOffset) { builder.AddOffset(0, keyOffset.Value, 0); }
  public static void AddText(FlatBufferBuilder builder, StringOffset textOffset) { builder.AddOffset(1, textOffset.Value, 0); }
  public static Offset<ZZZ_TextMap.Defs.TextMap> EndTextMap(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ZZZ_TextMap.Defs.TextMap>(o);
  }
  public TextMapT UnPack() {
    var _o = new TextMapT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TextMapT _o) {
    _o.Key = this.Key;
    _o.Text = this.Text;
  }
  public static Offset<ZZZ_TextMap.Defs.TextMap> Pack(FlatBufferBuilder builder, TextMapT _o) {
    if (_o == null) return default(Offset<ZZZ_TextMap.Defs.TextMap>);
    var _key = _o.Key == null ? default(StringOffset) : builder.CreateString(_o.Key);
    var _text = _o.Text == null ? default(StringOffset) : builder.CreateString(_o.Text);
    return CreateTextMap(
      builder,
      _key,
      _text);
  }
}

public class TextMapT
{
  [Newtonsoft.Json.JsonProperty("key")]
  public string Key { get; set; }
  [Newtonsoft.Json.JsonProperty("text")]
  public string Text { get; set; }

  public TextMapT() {
    this.Key = null;
    this.Text = null;
  }
}


static public class TextMapVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Key*/, false)
      && verifier.VerifyString(tablePos, 6 /*Text*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
